import {StyleSheet} from 'react-native'
import Colors from '../../themes/Colors'

export default StyleSheet.create({
    container:{
        flex:1,
        marginHorizontal:16
    },
    header:{
        marginVertical:10,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:"center"
    },
    header_text:{
        fontSize:24,
        marginLeft:32
    },
    header_right:{
        flexDirection:'row'
    },
    settings:{
        marginLeft:20
    },
    avatar:{
        height:50,
        width:50
    },
    avatar_container:{
        marginTop:20,
        flexDirection:'row',
        alignItems:'center'
    },
    avatar_right:{
        marginLeft:10,
        marginRight:15,
        height:50,
        justifyContent:'space-around'
    },
    name:{
        fontSize:19,
        color: Colors.gray_text2,
        marginRight:15
    },
    mail:{
        fontSize:15,
        color: Colors.gray_text1
    },
    name_container:{
        flexDirection:'row'
    },
    check:{
        paddingTop:3
    },
    status_container:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:30
    },
    total_love:{
        width:'48%',
        backgroundColor:Colors.purple,
        padding:16,
        borderRadius:5
    },
    matched:{
        width:'48%',
        backgroundColor:Colors.red_pink,
        padding:16,
        borderRadius:5
    },
    text_status:{
        fontSize:15,
        color:Colors.white
    },
    number_status:{
        fontSize:27,
        color:Colors.white,
        marginTop:8
    },
    action_container:{
        marginTop:30
    },
    block:{
        backgroundColor:Colors.white,
        flexDirection:'row',
        alignItems:'center',
        padding:16,
        justifyContent:'space-between',
        marginTop:12,
        borderRadius:8
    },
    icon_container:{
        height:56,
        width:56,
        borderRadius:28,
        backgroundColor: Colors.pink,
        justifyContent:'center',
        alignItems:'center',
        marginRight:16
    },
    action_info:{
        width:'65%',
        justifyContent:'center'
    },
    text_action:{
        color: Colors.gray_text,
        fontSize:17,
    },
    sub_text_action:{
        fontSize:13,
        color: Colors.gray_text,
        marginTop:8
    },
    action_left:{
        flexDirection:'row'
    }
})